### PR TITLE
question 1 complete -- close #2

### LINKED ISSUE #2: Q1 - SQL
(10 marks) Show all papers* and allow one to be selected. Once a paper is selected, show the email of all reviewers that have reviewed the paper.

* Note: For Questions 1 and 2, show all papers in pages with each displayed page having 5 papers.  Allow users to go to the next or previous page by pressing either N or P.

### PR DESCRIPTION
**Pull request by aradu12**

### CODE REVIEW

**Comment by NinjaPerson24119** [comment]
Yo, give a basic change log so I know what I'm reading and don't merge without a review. There's a setting somewhere to prevent merging without at least one review / approval, I'll have to set it. Also, we should be using squash merge.

**Comment by aradu12** [comment]
only changes I made was to complete question1 as in the title above and the assignment description. More specifically:
- added sql query to retrieve all papers
- added sql query to retrieve reviewers of a given paper
- added code to task1 function, which displays 5 papers per page and allows the user to choose one, and then shows reviewers for that paper
- added comments

**Comment by NinjaPerson24119** [comment]
You don't have to be as pedantic as me, but cool.

**Comment by NinjaPerson24119** [comment]
More notes: 
I think the UI would be better if the screen cleared (hence the existence of clear()) when changing pages.
It should probably display the current page and page count. I.e. Page 1/5, Page 2/3, etc.
Should the email list show duplicates?
Selecting papers on the second page results in an error
Should reference issues closed in the associated PR.
Following convention, rename 'Task1' to something descriptive in the API display

**Comment by aradu12** [comment]
- will fix that
- will add that
- the email list should show duplicates if an author has reviewed a paper more than once, as is the case in our database (probably an error in our Insert stmts?). One person reviewed a paper twice, and gave it different scores.
- see next comment
- the issue is referenced in the PR title

**Comment by aradu12** [comment]
Actually, hang on @NinjaPerson24119 , I pushed the right version. What are you getting as an error when selecting papers on the second page; I'm not getting any error

**Comment by NinjaPerson24119** [comment]
I deliberately added that duplicate reviewer as a test case. Probably more of a schema error than an us problem.
Yeah, it's in the title, but if you don't write the #X in the chat feed, the issue page won't ref the PR.
Also, delete the branch once it's merged so that it doesn't pollute: git branch -r

**Comment by NinjaPerson24119** [comment]
screenshot from 2019-03-06 01-26-06
The error occurs on the df2 = pd.read_sql_query line

**Comment by aradu12** [comment]
screen shot 2019-03-06 at 1 30 46 am

is what I'm getting, which seems fine. I'll add some more error checking just in case though.

**Comment by NinjaPerson24119** [comment]
We're clearly running different versions: yours has a page indicator. I'll reclone and try again.

**Comment by NinjaPerson24119** [comment]
Also, I'm noticing that trying to move to an out of bounds page doesn't give a descriptive error. It instead just repeats to enter on of n,p,#.

**Comment by NinjaPerson24119** [comment]
Cool, so now I get 2 errors:
screenshot from 2019-03-06 01-45-27

**Comment by aradu12** [comment]
I just deleted my local files and cloned again as well. I'm literally getting NO errors; it works perfectly.
Whatever, I'm going to bed and looking at it tomorrow lmaoo

**Pull request merged**
