### PR TITLE
Application skeleton

### PR DESCRIPTION
**Pull request by hughbagan**
This is a skeleton for the application's main loop. I thought that we would need at least this before we can start working on our own tasks.

### CODE REVIEW

**Comment by NinjaPerson24119** [comment]
A few points:
Why bother casting action to int when the case values can be strings? I.e. use action = '1'

That elif scheme doesn't scale, and the moment code is added to each case, it'll be unreadable. Since python doesn't support switch, we should use a map of functions, especially since some cases will require further user input.

There's no reasonable way to handle errors, so we shouldn't try to catch them. The program will exit anyway. If there are specific exceptions that specific functions can throw, we should wrap only those calls.

**Comment by NinjaPerson24119** [comment]
I would just define the dictionary func like dict = { a:b, c:d, e:f }, but it's pretty much the same thing.
lgtm for merge

**Comment by hughbagan** [comment]
Committed changes to reflect your suggestions.

Personally I think that simpler is better. I don't think an elif block would be unreadable, especially when tasks have their own functions. I think a function dictionary is a bit much for a small program like this. But I'm indifferent here, so I hope the new commit has what you were describing.

In the final submission we should make sure that our program fails gracefully, too. 

I made this pull request so that we could get a starting point for our code structure. Details for the loop can be hammered out later, but I need a `main.py` in the master branch to work from before I can start writing the tasks.

**Comment by NinjaPerson24119** [comment]
I mean, for an ideal SM, there'd be states in different files rather than one amalgam (further improving readability). 

If your intention was to put funcs in each elif, that's OK, I just thought you were going to inline it since you put a print in each case body. Best world is when python actually supports switch statements.

Yeah, but wrapping everything in a try/catch doesn't do graceful error handling, it just makes sure it prints a custom message before it crashes. At best, we just need to handle invalid input, which doesn't require exceptions. Maybe wrap DB connection stuff with exceptions too in case of missing files, but a complete try/catch wrap is horrible style unless cleanup actually needs to happen (say, writing to a log file, flushing a buffer, etc.)

**Pull request merged**
